//// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

//hola mundo
import domain.Usuarios;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import javax.swing.JOptionPane;


/************************************************************/
/**
 * 
 */
public class Autores extends Usuarios
 {

    public Autores(String unicoNombre, String contraseña, String nombreCompleto, String tipoIdentificacion, String identificacion,String tipoUsuario) {
//        
          super(unicoNombre, contraseña, nombreCompleto, tipoIdentificacion, identificacion,tipoUsuario);
    }

	/**
	 * 
	 */
	public void ListaObrasEscritas() {
	}

	@Override
	public boolean Borrar() {
		// TODO Auto-generated method stub
		return false;
	}

	
	public void Agregar(Autores au) {
		// TODO Auto-generated method stub
		 PrintStream ps = getPrintStream("Usuarios.txt");

        ps.println(au.getUnicoNombre() + ";" + au.getContraseña()+ ";" + au.getNombreCompleto()+ ";" + au.getTipoID() + ";" + au.getIdentificacion()+";"+au.gettipoUsuario());
	}
         public PrintStream getPrintStream(String nombreArchivo) {
        File archivo = new File(nombreArchivo);
        PrintStream ps = null;
        try {
            FileOutputStream fos = new FileOutputStream(archivo, true);
            ps = new PrintStream(fos);

        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(null, "error");
            
        }
        return ps;
    }

	@Override
	public boolean Buscar() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void Mostrar() {
		// TODO Auto-generated method stub
		
	}

    @Override
    public void Agregar(Bibliotecarios bi, Autores au) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
};
