// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

import domain.Autores;

/************************************************************/
/**
 * 
 */
public abstract class Catalogo {
     	protected Libros libros; 
    protected Memorias memorias;
    protected Revistas revistas;
    protected Tesis tesis;
    
    public Catalogo(String titulo, String fechaIngreso,String Autor) {
    	this. titulo =  titulo;
        this.fechaIngreso = fechaIngreso;
        this.Autor=Autor;
      
        
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getFechaIngreso() {
        return fechaIngreso;
    }

    public void setFechaIngreso(String fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public String getAutor() {
        return Autor;
    }

    public void setAutor(String Autor) {
        this.Autor = Autor;
    }
	/**
	 * 
	 */
	private String titulo;
	/**
	 * 
	 */
	private String fechaIngreso;
	/**
	 * 
	 */
	private String Autor;
};
