// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

import domain.Autores;

/************************************************************/
/**
 * 
 */
public abstract class Catalogo {
	/**
	 * 
	 */
	private String titulo;
	/**
	 * 
	 */
	private String fechaIngreso;
	/**
	 * 
	 */
	private Autores Autor;
};
