// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

import domain.Catalogo;

/************************************************************/
/**
 * 
 */
public class Libros extends Catalogo {
	/**
	 * 
	 */
	private String codigoISBN;
	/**
	 * 
	 */
	private String Tema;
	/**
	 * 
	 */
	private String subtema;
};
