// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import javax.swing.JOptionPane;

/************************************************************/
/**
 * 
 */
public class Libros extends Catalogo {
     public Libros(String titulo, String fechaIngreso, String Autor,String codigoISBN,String Tema,String subtema) {
        super(titulo, fechaIngreso, Autor);
        this.codigoISBN=codigoISBN;
        this.Tema=Tema;
        this.subtema=subtema;
    }



	/**
	 * 
	 */
	private String codigoISBN;
	/**
	 * 
	 */
	private String Tema;
	/**
	 * 
	 */
	private String subtema;

  

    public String getCodigoISBN() {
        return codigoISBN;
    }

    public void setCodigoISBN(String codigoISBN) {
        this.codigoISBN = codigoISBN;
    }

    public String getTema() {
        return Tema;
    }

    public void setTema(String Tema) {
        this.Tema = Tema;
    }

    public String getSubtema() {
        return subtema;
    }

    public void setSubtema(String subtema) {
        this.subtema = subtema;
    }
    public void Agregar(Libros libros) {
		// TODO Auto-generated method stub
	 PrintStream ps = getPrintStream("Libros.txt");

        ps.println(libros.getTitulo() + ";" + libros.getFechaIngreso()+ ";" + libros.getAutor()+ ";" + libros.getCodigoISBN() + ";" + libros.getTema()+";"+libros.getSubtema());
	}
    public PrintStream getPrintStream(String nombreArchivo) {
        File archivo = new File(nombreArchivo);
        PrintStream ps = null;
        try {
            FileOutputStream fos = new FileOutputStream(archivo, true);
            ps = new PrintStream(fos);

        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(null, "error");
            
        }
        return ps;
    }

} 