// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

import domain.Catalogo;

/************************************************************/
/**
 * 
 */
public class Revistas extends Catalogo {
	/**
	 * 
	 */
	private String codigoISSN;
	/**
	 * 
	 */
	private String edicion;

    public Revistas(String titulo, String fechaIngreso, String Autor,String codigoISSN,String edicion) {
        super(titulo, fechaIngreso, Autor);
        this.codigoISSN=codigoISSN;
        this.edicion=edicion;
    }

    public String getCodigoISSN() {
        return codigoISSN;
    }

    public void setCodigoISSN(String codigoISSN) {
        this.codigoISSN = codigoISSN;
    }

    public String getEdicion() {
        return edicion;
    }

    public void setEdicion(String edicion) {
        this.edicion = edicion;
    }
};
