// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

import domain.Catalogo;

/************************************************************/
/**
 * 
 */
public class Revistas extends Catalogo {
	/**
	 * 
	 */
	private String codigoISSN;
	/**
	 * 
	 */
	private String edicion;
};
