// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

import domain.Catalogo;

/************************************************************/
/**
 * 
 */
public class Tesis extends Catalogo {
	/**
	 * 
	 */
	private String Resumen;
	/**
	 * 
	 */
	private String Abstract;
};
