// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;


import domain.Usuarios;


/************************************************************/
/**
 * 
 */
public class Usuario extends Usuarios
 {
	/**
	 * 
	 */
	public void ListaObrasPrestadas() {
	}

	@Override
	public boolean Borrar() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void Agregar() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public boolean Buscar() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void Mostrar() {
		// TODO Auto-generated method stub
		
	}
};
