// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package domain;

/************************************************************/
/**
 * 
 */
public abstract class Usuarios {
	/**
	 * 
	 */
	private String unicoNombre;
	/**
	 * 
	 */
	private String contraseña;
	/**
	 * 
	 */
	private String nombreCompleto;
	/**
	 * 
	 */
	private String tipoID;
	/**
	 * 
	 */
	private String Identificacion;

	/**
	 * 
	 * @return 
	 */
	public abstract boolean Borrar();

	/**
	 * 
	 */
	public abstract void Agregar();

	/**
	 * 
	 * @return 
	 */
	public abstract boolean Buscar();

	/**
	 * 
	 */
	public void Modificar() {
	}

	/**
	 * 
	 */
	public abstract void Mostrar();
};
